initStore([
  {
    id: 0,
    title: 'Final Fantasy VII Rebirth (PS5)',
    description: 'Continue Cloud’s epic journey in this visually stunning reimagining of a beloved classic.',
    price: 69.99,
    discountPrice: 59.99,
    image: 'assets/img/service-1.jpg',
  },
  {
    id: 1,
    title: 'God of War Ragnarök (PS5)',
    description: 'Join Kratos and Atreus in their final Norse saga of gods and monsters.',
    price: 69.99,
    discountPrice: 54.99,
    image: 'assets/img/service-2.jpg',
  },
  {
    id: 2,
    title: 'Forza Motorsport (Xbox Series X/PC)',
    description: 'Experience next-gen racing realism with dynamic weather and track conditions.',
    price: 69.99,
    discountPrice: 49.99,
    image: 'assets/img/service-3.jpg',
  },
  {
    id: 3,
    title: 'Elden Ring: Shadow of the Erdtree (All platforms)',
    description: 'Expand the world of Elden Ring with this massive DLC full of new challenges.',
    price: 39.99,
    discountPrice: 34.99,
    image: 'assets/img/service-4.jpg',
  },
  {
    id: 4,
    title: 'Resident Evil 4 Remake (PS5/Xbox/PC)',
    description: 'A faithful and modernized remake of the survival horror classic.',
    price: 59.99,
    discountPrice: 44.99,
    image: 'assets/img/service-5.jpg',
  },
  {
    id: 5,
    title: 'Mario Kart 8 Deluxe (Nintendo Switch)',
    description: 'Speed through wild tracks with your favorite Nintendo characters.',
    price: 49.99,
    discountPrice: 39.99,
    image: 'assets/img/service-6.jpg',
  },
  {
    id: 6,
    title: 'The Legend of Zelda: Tears of the Kingdom (Switch)',
    description: 'Explore the skies and depths of Hyrule in this highly acclaimed sequel.',
    price: 69.99,
    discountPrice: 59.99,
    image: 'assets/img/service-7.jpg',
  },
  {
    id: 7,
    title: 'Starfield (Xbox/PC)',
    description: 'Embark on an epic space RPG adventure from the creators of Skyrim.',
    price: 69.99,
    discountPrice: 49.99,
    image: 'assets/img/service-8.jpg',
  }
]);
